// Pure declarative graph list + toggle rules, ported from legacy/Graphs.js graphList (L878) and
// toggledGraphs (L982). No DOM, no game, no echarts — conditionals read the injected GameDataReader,
// transforms delegate to ./transforms. (Enforced by tests/nets/graphs-purity.test.ts.)
import type { GraphDef, ToggleRule, ToggleId } from './types'
import { diff, perZone, perHr, lifetime, s3normalized } from './transforms'

// Each entry mirrors a `new Graph(dataVar, universe, selectorText, additionalParams)` call, with the
// Graph constructor defaults applied first (Graphs.js:391): graphType 'line', yType 'value' (legacy
// 'Linear'), xminFloor 1, formatterKind 'defaultPoint', id = selectorText.replace(/ /g,'_'),
// graphTitle = selectorText, conditional () => true. additionalParams override those.
export const GRAPH_LIST: GraphDef[] = [
  {
    dataVar: 'currentTime',
    universe: false,
    selectorText: 'Clear Time',
    id: 'Clear_Time',
    graphTitle: 'Clear Time',
    graphType: 'line',
    yType: 'datetime',
    xminFloor: 1,
    toggles: ['perZone', 'mapTime', 'mapCount'],
    conditional: () => true,
    formatterKind: 'datetime',
  },
  // U1 Graphs
  {
    dataVar: 'heliumOwned',
    universe: 1,
    selectorText: 'Helium',
    id: 'Helium',
    graphTitle: 'Helium',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    toggles: ['perHr', 'perZone', 'lifetime'],
    conditional: () => true,
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'fluffy',
    universe: 1,
    selectorText: 'Fluffy Exp',
    id: 'Fluffy_Exp',
    graphTitle: 'Fluffy Exp',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    toggles: ['perHr', 'perZone'],
    customFunction: (portal, i) => diff('fluffy', portal.initialFluffy)(portal, i),
    conditional: (g) => g.u1hze() >= 299 && g.fluffy() < 3413330078125000,
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'essence',
    universe: 1,
    selectorText: 'Dark Essence',
    id: 'Dark_Essence',
    graphTitle: 'Dark Essence',
    graphType: 'line',
    yType: 'value',
    xminFloor: 181,
    toggles: ['perHr', 'perZone'],
    customFunction: (portal, i) => diff('essence', portal.initialDE)(portal, i),
    conditional: (g) => g.essence() < 5.826e39,
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'lastWarp',
    universe: 1,
    selectorText: 'Warpstations',
    id: 'Warpstations',
    graphTitle: 'Warpstations built on previous Giga',
    graphType: 'line',
    yType: 'value',
    xminFloor: 60,
    conditional: (g) => g.u1hze() >= 59 && g.totalHeliumEarned() - g.heliumLeftover() < 10 ** 10,
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'amals',
    universe: 1,
    selectorText: 'Amalgamators',
    id: 'Amalgamators',
    graphTitle: 'Amalgamators',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    conditional: () => true,
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'wonders',
    universe: 1,
    selectorText: 'Wonders',
    id: 'Wonders',
    graphTitle: 'Wonders',
    graphType: 'line',
    yType: 'value',
    xminFloor: 300,
    conditional: (g) => g.challengeActive() === 'Experience',
    formatterKind: 'defaultPoint',
  },
  // U2 Graphs
  {
    dataVar: 'radonOwned',
    universe: 2,
    selectorText: 'Radon',
    id: 'Radon',
    graphTitle: 'Radon',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    toggles: ['perHr', 'perZone', 'lifetime', 's3normalized'],
    conditional: () => true,
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'scruffy',
    universe: 2,
    selectorText: 'Scruffy Exp',
    id: 'Scruffy_Exp',
    graphTitle: 'Scruffy Exp',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    toggles: ['perHr', 'perZone'],
    customFunction: (portal, i) => diff('scruffy', portal.initialScruffy)(portal, i),
    conditional: () => true,
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'mutatedSeeds',
    universe: 2,
    selectorText: 'Mutated Seeds',
    id: 'Mutated_Seeds',
    graphTitle: 'Mutated Seeds',
    graphType: 'line',
    yType: 'value',
    xminFloor: 200,
    toggles: ['perHr', 'perZone'],
    customFunction: (portal, i) => diff('mutatedSeeds', portal.initialMutes)(portal, i),
    conditional: (g) => g.u2hze() >= 200,
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'worshippers',
    universe: 2,
    selectorText: 'Worshippers',
    id: 'Worshippers',
    graphTitle: 'Worshippers',
    graphType: 'line',
    yType: 'value',
    xminFloor: 50,
    conditional: (g) => g.u2hze() >= 49,
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'smithies',
    universe: 2,
    selectorText: 'Smithies',
    id: 'Smithies',
    graphTitle: 'Smithies',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    conditional: () => true,
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'bonfires',
    universe: 2,
    selectorText: 'Bonfires',
    id: 'Bonfires',
    graphTitle: 'Active Bonfires',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    conditional: (g) => g.challengeActive() === 'Hypothermia',
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'embers',
    universe: 2,
    selectorText: 'Embers',
    id: 'Embers',
    graphTitle: 'Embers',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    conditional: (g) => g.challengeActive() === 'Hypothermia',
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'cruffys',
    universe: 2,
    selectorText: 'Cruffys',
    id: 'Cruffys',
    graphTitle: 'Cruffys',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    conditional: (g) => g.challengeActive() === 'Nurture',
    formatterKind: 'defaultPoint',
  },
  // Generic Graphs
  {
    dataVar: 'c23increase',
    universe: false,
    selectorText: 'C2 Bonus',
    id: 'C2_Bonus',
    graphTitle: 'C2 Bonus',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    toggles: ['perHr', 'perZone', 'lifetime'],
    conditional: (g) => g.runningChallengeSquared(),
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'voids',
    universe: false,
    selectorText: 'Void Map History',
    id: 'Void_Map_History',
    graphTitle: 'Void Map History (voids finished during the same level acquired are not counted/tracked)',
    yTitle: 'Number of Void Maps',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    conditional: () => true,
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'coord',
    universe: false,
    selectorText: 'Coordinations',
    id: 'Coordinations',
    graphTitle: 'Unbought Coordinations',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    conditional: () => true,
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'overkill',
    universe: false,
    selectorText: 'Overkill Cells',
    id: 'Overkill_Cells',
    graphTitle: 'Overkill Cells',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    conditional: (g) =>
      (g.universe() === 1 && g.u1hze() >= 169) || (g.universe() === 2 && g.u2hze() >= 200),
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'mapbonus',
    universe: false,
    selectorText: 'Map Bonus',
    id: 'Map_Bonus',
    graphTitle: 'Map Bonus',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    conditional: () => true,
    formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'empower',
    universe: false,
    selectorText: 'Empower',
    id: 'Empower',
    graphTitle: 'Empower',
    graphType: 'line',
    yType: 'value',
    xminFloor: 1,
    conditional: (g) => g.challengeActive() === 'Daily' && g.empowerDefined(),
    formatterKind: 'defaultPoint',
  },
  // Multi-axis column chart (Graphs.js:964)
  {
    dataVar: false,
    universe: false,
    selectorText: 'Portal Stats',
    id: 'Portal_Stats',
    graphTitle: 'Portal Stats',
    graphType: 'column',
    yType: 'value',
    xminFloor: 1,
    toggles: ['perHr'],
    columns: [
      { dataVar: 'totalVoidMaps', title: 'Voids', color: '#4d0e8c' },
      { dataVar: 'totalNullifium', title: 'Nu', color: '#8a008a' },
      { dataVar: 'heliumOwned', universe: 1, title: 'Helium', color: '#5bc0de' },
      { dataVar: 'radonOwned', universe: 2, title: 'Radon', color: '#5bc0de' },
      {
        dataVar: 'fluffy',
        universe: 1,
        title: 'Pet Exp',
        color: 'green',
        customFunction: (portal, x) => x - portal.initialFluffy!,
      },
      {
        dataVar: 'scruffy',
        universe: 2,
        title: 'Pet Exp',
        color: 'green',
        customFunction: (portal, x) => x - portal.initialScruffy!,
      },
      { dataVar: 'currentTime', title: 'Run Time', type: 'datetime', color: '#928DAD' },
    ],
    conditional: () => true,
    formatterKind: 'defaultPoint',
  },

  // #135 — new progression graphs (universe-agnostic, per-zone).
  {
    dataVar: 'population', universe: false, selectorText: 'Population', id: 'Population',
    graphTitle: 'Max Population', graphType: 'line', yType: 'value', xminFloor: 1,
    conditional: () => true, formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'gearLevels', universe: false, selectorText: 'Gear Levels', id: 'Gear_Levels',
    graphTitle: 'Total Equipment Levels', graphType: 'line', yType: 'value', xminFloor: 1,
    conditional: () => true, formatterKind: 'defaultPoint',
  },
  {
    dataVar: 'playerDamage', universe: false, selectorText: 'Damage', id: 'Damage',
    graphTitle: 'Player Damage', graphType: 'line', yType: 'log', xminFloor: 1,
    conditional: () => true, formatterKind: 'defaultPoint',
  },
  {
    // % of each zone's time spent in maps. dataVar 'currentTime' so every zone is iterated (incl. 0%
    // no-map zones); the customFunction reads the accumulated timeOnMap for that zone.
    dataVar: 'currentTime', universe: false, selectorText: 'Time in Maps %', id: 'Time_in_Maps',
    graphTitle: '% of Zone Spent in Maps', yTitle: '% in Maps', graphType: 'line', yType: 'value', xminFloor: 1,
    customFunction: (portal, i) => {
      const zoneTime = (portal.perZoneData.currentTime[i] as number) - (portal.perZoneData.currentTime[i - 1] as number)
      return zoneTime > 0 ? ((portal.perZoneData.timeOnMap[i] || 0) / zoneTime) * 100 : 0
    },
    conditional: () => true, formatterKind: 'defaultPoint',
  },

  // #135 — He/hr efficiency curves (TIME-sampled, not per-zone). dataVar:false so nothing is captured
  // per-zone; option-builder reads portal.hehrSamples. The '1hr' toggle coarsens 15-min → 1-hr points.
  {
    dataVar: false, universe: 1, selectorText: 'Helium / Hour', id: 'Helium_per_Hour',
    graphTitle: 'Helium / Hour', graphType: 'line', yType: 'value', xminFloor: 0,
    timeSeries: true, toggles: ['1hr'], conditional: () => true, formatterKind: 'defaultPoint',
  },
  {
    dataVar: false, universe: 2, selectorText: 'Radon / Hour', id: 'Radon_per_Hour',
    graphTitle: 'Radon / Hour', graphType: 'line', yType: 'value', xminFloor: 0,
    timeSeries: true, toggles: ['1hr'], conditional: () => true, formatterKind: 'defaultPoint',
  },
]

// Toggle rules — the declarative form of legacy toggledGraphs (Graphs.js:982). The legacy
// `graphMods` closures (title/axis mutations) become data fields; the numeric `customFunction`
// becomes `transform`, delegating to ./transforms. option-builder applies these later.
export const TOGGLE_RULES: Record<ToggleId, ToggleRule> = {
  mapCount: {
    exclude: ['mapTime', 'mapPct'],
    useAccumulator: true,
    titleOverride: 'Maps Run',
    yAxisName: 'Maps Run',
    yAxisType: 'value',
    useDefaultPointFormatter: true,
    transform: (p, _item, index) => p.perZoneData.mapCount[index] || 0,
  },
  mapTime: {
    exclude: ['mapCount', 'mapPct'],
    useAccumulator: true,
    titleOverride: 'Time in Maps',
    transform: (p, _item, index) => p.perZoneData.timeOnMap[index] || 0,
  },
  mapPct: {
    exclude: ['mapCount', 'mapTime'],
    useAccumulator: true,
    titleOverride: '% of Clear time spent Mapping',
    yAxisName: '% Clear Time',
    yAxisType: 'value',
    useDefaultPointFormatter: true,
    transform: (p, _item, index, x) => (p.perZoneData.timeOnMap[index] as number) / x || 0,
  },
  perZone: {
    useAccumulator: false,
    titleSuffix: ' each Zone',
    transform: (p, item, index) => perZone(p, item, index),
  },
  perHr: {
    titleSuffix: ' / Hour',
    transform: (_p, _item, _index, x, time) => perHr(x, time),
  },
  lifetime: {
    titleSuffix: ' % of Lifetime Total',
    yAxisNameSuffix: ' % of lifetime',
    transform: (p, item, _index, x) => lifetime(p, item, x),
  },
  s3normalized: {
    titleSuffix: (ctx) => `, Normalized to z${ctx.maxS3} S3`,
    transform: (p, _item, _index, x, _time, maxS3) => s3normalized(x, p.s3 ?? 0, maxS3),
  },
  // #135 — only used by the He/hr time-series graph; its effect (coarsen 15-min → 1-hr points) is applied
  // directly in option-builder's time-series path, not through the perZone transform pipeline. This entry
  // just satisfies Record<ToggleId, ToggleRule> and lets the checkbox render. Identity transform.
  '1hr': {
    titleSuffix: ' (hourly)',
    transform: (_p, _item, _index, x) => x,
  },
}
